name: build-and-deploy-to-caprover
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy-to-caprover:
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04
    environment: production
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
          uses: docker/build-push-action@v3
          with:
            # Note: tags has to be all lower-case
            tags: ${{secrets.DOCKERHUB_USERNAME}}/portfolio
            # build on feature branches, push only on main branch
            push: ${{ github.ref == 'refs/heads/main' }}

      - name: Deploy to CapRover
        run: docker run caprover/cli-caprover:v2.1.1 caprover deploy --caproverUrl ${{ secrets.CAPROVER_URL }} --caproverPassword ${{ secrets.CAPROVER_PASSWORD }} --caproverApp ${{ secrets.CAPROVER_APP }} --imageName "${{secrets.DOCKERHUB_USERNAME}}/portfolio"